### PR TITLE
Add help page in the settings screen.

### PR DESCRIPTION
**Pull request by RebelliousX**
Help menu item is added to settings, and when selected,
it will load a HTML page that is bundled with the app.

I tried to be verbose with explaining every aspect of the app.
It currently has English and Japanese manuals. 

https://github.com/wa2c/cifs-documents-provider/assets/1888186/839cfa6c-85f0-4f73-bd9f-b7bcfb3b100f

### CODE REVIEW

**Comment by RebelliousX** [comment]
This is a draft, but I believe the English part is finished.
The Japanese manual is unfortunately is outdated, I took it
from the WIKI of this repo. Unfortunately after  many years
of watching Anime, my Japanese vocabulary words are handful,
lol. So basically, I didn't want to use Google translate for that.

Please fee free to modify "ANY" part or anything in the HTML file.

Here is archive of the HTML file and images used for the manual.
[Help.zip](https://github.com/wa2c/cifs-documents-provider/files/14076440/Help.zip)

Edit: I found few typos, I will edit them later.

**Comment by wa2c** [comment]
Thanks, but I editing manual pages now.
Please wait for a while for the response to this Issue.

**Comment by RebelliousX** [comment]
Here is an updated version of the [Help Manual](https://docs.google.com/document/d/e/2PACX-1vRxDb6VVN48ct8hKfDqjVbutdkHMLJIHSTmCUKAKuH96xnKe7q2_m_eq0iWBvt-D-SngloOGTuqHbWQ/pub) from Google Docs. It has the updated Japanese Manual.

Feel free to modify it as you like, once you are done, go to `File->Download->Webpage HTML (zipped file)`
Extract the zipped file and copy `Help.html` and `images` directory, then delete (safer to delete than replace, in case there are orphan images) existing files in the `assets` folder under `projectDir\presentation\src\main\assets` and paste the new one files.

[Help.zip](https://github.com/wa2c/cifs-documents-provider/files/14241132/Help.zip)

**Comment by wa2c** [comment]
Sorry, I have no plans to include help within the app.

* The size of resources such as images increases unnecessarily.
* Too expensive to update and maintain
* Don't feel the need to put help inside the app

I would like to limit this to just creating a link to the manual page.

**Comment by RebelliousX** [comment]
I understand, the increase in size is an issue, no worries, I just trying to help 😊

I agree, we can limit this to just a link to the manual page.
Is there a way to submit help manual to your wiki?

**Pull request closed without merging**
